name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Spécifiez la version de Python que vous utilisez

    - name: Install dependencies with Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev # ou la commande spécifique pour installer les dépendances avec Pipenv
