# Generated by Django 4.2.5 on 2023-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='video_1080p',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_120fps',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_240fps',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_30fps',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_480fps',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_4K',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_60fps',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_720p',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_8K',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_960fps',
            field=models.BooleanField(null=True),
        ),
    ]
