# Generated by Django 4.1.3 on 2023-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historiquevisite_alter_phone_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquevisite',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
