# Generated by Django 4.2.5 on 2023-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_phone_announcement_date_alter_phone_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
