# Generated by Django 4.1.3 on 2023-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historiquevisite_date_of_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquevisite',
            old_name='phone_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='historiquevisite',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
