# Generated by Django 4.1.3 on 2023-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_souhaits'),
    ]

    operations = [
        migrations.AddField(
            model_name='souhaits',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Clôturé', 'Clôturé'), ('Annulé', 'Annulé')], default='En attente', max_length=50),
        ),
    ]
