
# Generated by Django 4.1.3 on 2023-11-27 14:37

# Generated by Django 4.2.5 on 2023-11-27 14:41

# Generated by Django 4.2.5 on 2023-11-27 14:41
# Generated by Django 4.1.3 on 2023-11-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phone_new_price'),
        ('api', '0008_alter_souhaits_status'),
    ]

    operations = [
    ]
