# Generated by Django 4.1.3 on 2023-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_historiquevisite_prix_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='name',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to='api.souhaits'),
        ),
    ]
