# Generated by Django 4.2.5 on 2023-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
