# Generated by Django 4.1.3 on 2023-12-15 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_sujet_commentaire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaire',
            new_name='Commentaire_telephone',
        ),
        migrations.RenameModel(
            old_name='Sujet',
            new_name='Sujet_telephone',
        ),
        migrations.RenameField(
            model_name='commentaire_telephone',
            old_name='sujet',
            new_name='sujet_telephone',
        ),
    ]
