# Generated by Django 4.2.5 on 2023-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_personne_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
