# Generated by Django 4.1.3 on 2023-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_sujet_accessoire_tablette_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('etoiles', models.FloatField()),
                ('evaluations', models.IntegerField()),
                ('avis', models.IntegerField()),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processeur', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('stockage', models.CharField(max_length=255)),
                ('url_image', models.URLField()),
            ],
        ),
    ]
