# Generated by Django 4.1.3 on 2023-12-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ordinateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinateur',
            name='prix_actuel',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='prix_mrp',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
