# Generated by Django 4.2.5 on 2023-12-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_groupeutilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupeUtilisateur',
        ),
    ]
