# Generated by Django 4.2.5 on 2023-12-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_meeting_brand_remove_meeting_name_and_more'),
        ('api', '0026_delete_groupeutilisateur'),
    ]

    operations = [
    ]
