# Generated by Django 4.2.5 on 2023-12-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_phone_video_1080p_alter_phone_video_120fps_and_more'),
        ('api', '0027_merge_20231203_1625'),
    ]

    operations = [
    ]
