# Generated by Django 4.2.5 on 2023-12-15 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_merge_20231215_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invitation_status',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_1080p',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_120fps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_240fps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_30fps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_480fps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_4K',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_60fps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_720p',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_8K',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_960fps',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
