# Generated by Django 4.2.5 on 2023-12-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_budjet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('souhait', 'Budjet pour un Souhait'), ('meet', 'Budjet pour un Meet')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
                ('souhait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.souhaits')),
            ],
        ),
        migrations.DeleteModel(
            name='Budjet',
        ),
    ]
