# Generated by Django 4.2.5 on 2023-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_budget_delete_budjet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('souhait', 'Budget pour un Souhait'), ('meet', 'Budget pour un Meet')], max_length=10),
        ),
    ]
