# Generated by Django 4.2.5 on 2023-12-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
        migrations.AddField(
            model_name='invitation',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitee_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitee_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
