# Generated by Django 4.1.3 on 2023-12-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_ordinateur_prix_actuel_and_more'),
        ('api', '0031_budget_user'),
    ]

    operations = [
    ]
