# Generated by Django 4.1.3 on 2024-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20231216_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('shop', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('addr_housenumber', models.CharField(blank=True, max_length=255)),
                ('addr_street', models.CharField(blank=True, max_length=255)),
                ('addr_city', models.CharField(blank=True, max_length=255)),
                ('addr_postcode', models.CharField(blank=True, max_length=255)),
                ('the_geom', models.TextField()),
                ('osm_original_geom', models.TextField()),
                ('osm_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
