# Generated by Django 4.2.5 on 2023-12-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_favoritephone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritePhone',
        ),
    ]
