# Generated by Django 4.2.5 on 2023-12-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20231216_1220'),
        ('api', '0036_remove_meeting_invitation_status_and_more'),
    ]

    operations = [
    ]
