# Generated by Django 5.0.3 on 2024-03-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_mobileshop"),
        ("api", "0037_merge_20231216_1625"),
        ("api", "0037_merge_20231216_1649"),
    ]

    operations = []
