# Generated by Django 4.1.3 on 2024-03-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_mobileshop'),
        ('api', '0037_merge_20231216_1649'),
    ]

    operations = [
    ]
